[package]
name = "fast_plaid_rust"
version = "1.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "fast_plaid_rust"
crate-type = ["cdylib"]
path = "rust/lib.rs"

[dependencies]
anyhow = "1.0.98"
tch = { version = "0.20.0" }
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
libc = "0.2.172"
parking_lot = "0.12.3"
once_cell = "1.21.3"
indicatif = "0.17.11"
pyo3 = { version = "0.24.0", features = ["extension-module"] }
pyo3-tch = "0.20.0"
rand = "0.9.1"
regex = "1.11.1"

# Windows-specific dependencies
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["libloaderapi", "errhandlingapi"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
